language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t patrickvieira1/react-test -f ./fibonacci/complex/client/Dockerfile.dev .

script:
  - docker run -e CI=true patrickvieira1/react-test npm test -- --coverage

after_success:
  - docker build -t patrickvieira1/multi-client ./fibonacci/complex/client/
  - docker build -t patrickvieira1/multi-nginx ./fibonacci/complex/nginx/
  - docker build -t patrickvieira1/multi-server ./fibonacci/complex/server/
  - docker build -t patrickvieira1/multi-worker ./fibonacci/complex/worker/
  #Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to Docker Hub

  - docker push patrickvieira1/multi-client
  - docker push patrickvieira1/multi-nginx
  - docker push patrickvieira1/multi-server
  - docker push patrickvieira1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-374015130602'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY